on:
  push:
    branches: 
      - main
    
jobs:
  Main_CI:
    name: Main CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install Deps
        run: yarn install
    
      - name: Build Lib
        run: yarn build

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy Preview
        id: deploy
        run: netlify deploy --dir "storybook-static" --alias "staging" --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_PEBBLES_ID }}
