on: workflow_dispatch

jobs:
  Release_CI:
    name: Release CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install Deps
        run: yarn install

      - name: Build Lib
        run: yarn build

      - name: Build Storybook
        run: yarn build-storybook

      - name: Create Release
        env:
          GIT_AUTHOR_NAME: "@logrock-eng"
          GIT_AUTHOR_EMAIL: engineering@logrock.com
          GIT_COMMITTER_NAME: "@logrock-eng"
          GIT_COMMITTER_EMAIL: engineering@logrock.com
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_WEBHOOK }}
        run: yarn semantic-release

      - name: Deploy Storybook
        id: deploy
        run: netlify deploy --dir "storybook-static" --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_PEBBLES_ID }} --prod
